# Generated by Django 3.1.1 on 2020-09-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
